### ISSUE TITLE
Colour codes on Sketch File do not match those on Zeplin

### ISSUE THREAD

**Issue by oise** [thePlaybookTV/PlayKit-UI#10]
Colour code on the Zeplin styleguide page doesn't match the styleguide in sketch.
![image](https://user-images.githubusercontent.com/11674268/29274936-67337732-8101-11e7-8f2a-dc732984d8e7.png)
![image](https://user-images.githubusercontent.com/11674268/29275024-a135acac-8101-11e7-853a-54a69f3af00c.png)

Or maybe the [use cases] are just missing.

**Comment by xekushuna** [comment]
This should have been patched by now. Raise another issue if negative.
